version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./schema/init.up.sql:/docker-entrypoint-initdb.d/init.up.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - lime_network

  eth-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:8080'
    environment:
      - API_PORT=8080
      - DB_CONNECTION_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - ETH_NODE_URL=${ETH_NODE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - lime_network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - lime_network

networks:
  lime_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
